version: '3.9'
services:
  nestapp:
    container_name: vvdev_nest_server
    image: temiksvyatov/vvdev_nest_server:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=vvdev_nest_db
      - PG_PORT=5432
      - PG_HOST=db
    depends_on:
      - db
  db:
    container_name: vvdev_nest_db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vvdev_nest_db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
